# Generated by Django 6.1.1 on 2026-09-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='level',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
